name: FLOW CI

on:
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  call-workflow2-1:
    if: success()
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit

  call-workflow2-2:
    if: failure()
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit