name: FLOW CI

on:
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  filter-path:
    runs-on: Linux
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
      ctp: ${{ steps.filter.outputs.ctp }}
      is: ${{ steps.filter.outputs.is }}
    steps:
      - name: filterPath Step
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ui:
              - 'Folder1/**'
            ctp:
              - 'Folder2/**'
            is:
              - 'Folder3/**'

  auto-label:
    needs: filter-path
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit
  
  call-workflow2job:
    needs: auto-label
    uses: ./.github/workflows/callWorkflow2.yml
    secrets: inherit

  call-workflow-ci-ui:
    needs: [ call-workflow2job ]
    if: ${{ needs.filter-path.outputs.ui == 'true' }}
    uses: ./.github/workflows/ci-ui.yml
    secrets: inherit

  call-workflow-ci-ctp:
    needs: [ call-workflow2job ]
    if: ${{ needs.filter-path.outputs.ctp == 'true' }}
    uses: ./.github/workflows/ci-ctp.yml
    secrets: inherit

  call-workflow-ci-is:
    needs: [ call-workflow2job ]
    if: ${{ needs.filter-path.outputs.is == 'true' }}
    uses: ./.github/workflows/ci-is.yml
    secrets: inherit

  call-workflow2-parallel:
    needs: [ call-workflow-ci-ui, call-workflow-ci-ctp, call-workflow-ci-is ]
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit
