name: FLOW CI

on:
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  # filter-path:
  #   runs-on: Linux
  #   steps:
  #     - name: filterPath Step
  #       uses: AIM/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           backend:
  #             - 'modules/**'
  #             - 'packages/**'
  #           frontend:
  #             - 'webapps/**'
  #           scripts:
  #             - scripts/**

  auto-label:
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit

  call-workflow-ci-ui:
    needs: auto-label
    if: ${{ contains(github.event.pull_request.labels.*.name, 'flow-ui-fix') && !contains(github.event.pull_request.labels.*.name, 'flow-ctp-fix') && !contains(github.event.pull_request.labels.*.name, 'flow-is-fix') }}
    uses: ./.github/workflows/ci-ui.yml
    secrets: inherit

  call-workflow-ci-ctp:
    needs: auto-label
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'flow-ui-fix') && contains(github.event.pull_request.labels.*.name, 'flow-ctp-fix') && !contains(github.event.pull_request.labels.*.name, 'flow-is-fix') }}
    uses: ./.github/workflows/ci-ctp.yml
    secrets: inherit

  call-workflow-ci-is:
    needs: auto-label
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'flow-ui-fix') && !contains(github.event.pull_request.labels.*.name, 'flow-ctp-fix') && contains(github.event.pull_request.labels.*.name, 'flow-is-fix') }}
    uses: ./.github/workflows/ci-is.yml
    secrets: inherit

  call-workflow2-parallel:
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit