name: test workflow 1

on:
  workflow_dispatch:

permissions: write-all

jobs:
  call-workflow2:
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit
  
  call-workflow3:
    uses: ./.github/workflows/test-workflow3.yml
    secrets: inherit
