name: test workflow 1

on:
  workflow_call:

permissions: write-all

jobs:
  call-workflow2:
    uses: ./.github/workflows/test-workflow22.yml
    secrets: inherit
  
  call-workflow3:
    uses: ./.github/workflows/test-workflow33.yml
    secrets: inherit

  call-workflow2-again:
    needs: [call-workflow2, call-workflow3]
    uses: ./.github/workflows/test-workflow22.yml
    secrets: inherit
