name: test workflow 1

on:
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  call-workflow2:
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit
  
  call-workflow3:
    needs: call-workflow2
    uses: ./.github/workflows/test-workflow3.yml
    secrets: inherit
